name: Deploy Cloud Run

on: [push]

jobs:

  testing-action:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: gcp-ts-cloudrun

    steps:
      # checkout code
      - uses: actions/checkout@v3

      # setup node (typescript)
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "npm install"
        run: npm install

      # auth GCP
      - name: "auth GCP"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_TOKEN }}"

      # setup gcloud cli
      - name: "setup GCP"
        uses: "google-github-actions/setup-gcloud@v1"

      # configure gcr.io
      - name: "configure gcr.io"
        run: gcloud auth configure-docker gcr.io

      # pulumi stack initialization
      - name: Initialize Pulumi Stack
        run: |
          if ! pulumi stack select dev --non-interactive 2>/dev/null; then
            pulumi stack init dev
          fi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
      
      - name: "exec pulumi"
        uses:  pulumi/actions@v3
        with:
          command: up
          stack-name: clecioantao/gcp-ts-cloudrun/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}